before_script:
  - "psql --version"
  - "psql -c 'CREATE DATABASE travis_ci_test;' -U postgres"
  - 'psql -c "CREATE USER test WITH PASSWORD ''1234'';" -U postgres'
  - 'psql -c "ALTER DATABASE travis_ci_test OWNER TO test;" -U postgres'
env:
  global:
    - "TEST_DB_URL=postgres://test:1234@localhost:5432/travis_ci_test"
    -"SECRET=SECRET"
    - "MEETUP_KEY=MEETUP_KEY"
    - CODECOV_TOKEN=65e214e6-d134-471c-b66e-fa5341b6f5c0
install:
  - "npm install"
  - "npm install -g codecov"
language: node_js
node_js:
  - node
script:
  - "npm test"
services:
  - postgresql
