language: node_js
node_js:
  - "node"

install:
  - npm install
  - npm install -g codecov

script:
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov

services:
  - postgresql

env:
  - TEST_DB_URL=postgres://test:1234@localhost:5432/travis_ci_test

before_script:
  - psql --version
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - psql -c "CREATE USER test WITH PASSWORD '1234';" -U postgres
  - psql -c "ALTER DATABASE travis_ci_test OWNER TO test;" -U postgres
