BEGIN;

DROP TABLE IF EXISTS users, teams, events CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  team Text,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  email VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE teams (
  id SERIAL PRIMARY KEY,
  name Text,
  location TEXT,
  user_id INTEGER REFERENCES users(id),
  size INTEGER,
  genders INTEGER,
  ages INTEGER,
  skill INTEGER,
  sport TEXT,
  solo  BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE events (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  sport TEXT NOT NULL,
  users_id INTEGER REFERENCES users(id),
  location TEXT NOT NULL,
  genders INTEGER,
  open BOOLEAN NOT NULL DEFAULT false
);

INSERT INTO users (team, username, password, email) VALUES
(  '',  'Sasspants_sally',   'password',  'grahlsan@gmail.com'),
('footy',  'charlie', 'ilovefootball', 'charlie@gmail.com'),
  ('Stringtough', 'Bowler', 'nmjV9XviN7', 'rbowler0@twitpic.com') ,
  ('Gembucket', 'Woolgar', 'FQCvxNNaA', 'vwoolgar1@hibu.com') ,
('Otcom', 'Gellett', 'N2nY1PUW', 'fgellett2@domainmarket.com') ,
  ('Sonsing', 'Soars', 't96bgPATX', 'msoars3@ox.ac.uk') ,
  ('Wrapsafe', 'Chalke', 'WVbhR7rB', 'bchalke4@wunderground.com') ,
  ('Bamity', 'Qualtro', 'q8otBuQ1', 'mqualtro5@hc.com') ,
  ('Asoka', 'Stork', '2WJikUjA8Y', 'fstork6@biglobe.ne.jp') ,
  ('Daltfresh', 'Shingles', 'jnKkKK', 'cshingles7@livejournal.com') ,
  ('Veribet', 'Geeson', '9qnpG5Taz1N', 'tgeeson8@arstechnica.com') ,
  ('Zontrax', 'Bodleigh', 'uANtCWkC', 'mbodleigh9@ustream.tv') ,
  ('Toughjoyfax', 'Luckhurst', 'VoHDUu69ss', 'fluckhursta@fema.gov') ,
  ('Transcof', 'Piffootball', '7SZEUwfD', 'tpiffootballb@hostgator.com') ,
  ('Bitwolf', 'Dufton', 'oRpHnoEI', 'gduftonc@wunderground.com') ,
  ('Overhold', 'Ricket', 'QfnBmU1', 'jricketd@whitehouse.gov') ,
  ('Daltfresh', 'Treske', 'uccFOEUwu', 'ctreskee@irs.gov') ,
  ('Alpha', 'Feares', 'GJuwdf', 'jfearesf@scribd.com') ,
  ('Konklab', 'Gabby', 'QoB7LOlI', 'lgabbyg@last.fm') ,
  ('Fix San', 'Cosgrove', 'vBk2FhRBwrmY', 'fcosgroveh@nydailynews.com') ,
  ('Pannier', 'Scryne', 'wXaIECT1K', 'nscrynei@creativecommons.org') ,
  ('Bitwolf', 'Hillan', 'SbGz62', 'ohillanj@earthlink.net') ,
  ('Zontrax', 'McAsgill', 'wndKzipt', 'cmcasgillk@ucsd.edu') ,
  ('Zontrax', 'Michell', '0oC2R7MK', 'gmichelll@phoca.cz') ,
  ('Rank', 'Hayen', 'U8PYunYd', 'dhayenm@webs.com') ,
  ('Lotstring', 'Bierling', 'ht8xG4sQZu', 'dbierlingn@edublogs.org') ,
  ('Temp', 'Burnhard', 'vdaYgTsV8o0', 'kburnhardo@timesonline.co.uk') ,
  ('Overhold', 'McKevin', 'MFJVsQHoiVQ', 'kmckevinp@ameblo.jp') ,
  ('Namfix', 'Weins', 'EfO5B4U', 'aweinsq@newsvine.com') ,
  ('Zontrax', 'Peirazzi', '3wM44Mf', 'lpeirazzir@mlb.com') ,
  ('Bamity', 'Ludron', '6fDAtR', 'wludrons@omniture.com') ,
  ('Flowdesk', 'Trunby', 'lHmnNIfMOV', 'jtrunbyt@imageshack.us') ,
  ('Fix San', 'Vinden', 'rVskZGqz', 'mvindenu@fotki.com') ,
  ('Aerified', 'Croux', 'I2ZLVIr', 'dcrouxv@artisteer.com') ,
  ('Tresom', 'Hamberston', 'rx96ThOzDP8m', 'ghamberstonw@indiegogo.com') ,
  ('Rank', 'Jenne', 'pPYZuwLX51', 'sjennex@gmpg.org') ,
  ('Ronstring', 'Devorill', 'pfootballpV', 'fdevorilly@studiopress.com') ,
  ('Namfix', 'McGerraghty', '1JDsZYAVU7n', 'mmcgerraghtyz@vinaora.com') ,
  ('Tres-Zap', 'Cleary', 'bIKW1D', 'fcleary10@fastcompany.com') ,
  ('Pannier', 'Loins', '5syMve4jlYD', 'nloins11@nsw.gov.au') ,
  ('Holdlamis', 'O''Quin', 'QGMW1l', 'doquin12@forbes.com') ,
  ('Mat Lam Tam', 'Toleman', 'cCcrQaL', 'gtoleman13@unc.edu') ,
  ('Zoolab', 'Woodfootball', 'UtWQIN4ze', 'mwoodfootball14@geocities.com') ,
  ('Greenlam', 'Appleby', '8TVwg9cfqk6', 'mappleby15@flickr.com') ,
  ('Lotstring', 'Avent', 'lfdtjuyc', 'tavent16@bbb.org') ,
  ('Fix San', 'Diehn', 'Y6lsZWfG', 'hdiehn17@prweb.com') ,
  ('Zontrax', 'Bethel', 'aUZCBmaIcpq', 'mbethel18@berkeley.edu') ,
  ('Stim', 'Metschke', 'rj8CFoK', 'mmetschke19@rakuten.co.jp') ,
  ('Lotlux', 'Macklam', 'dhkBJrtSGAyE', 'cmacklam1a@house.gov') ,
  ('Aerified', 'Kobieriecki', '9QwbxuENWC', 'okobieriecki1b@chronoengine.com') ,
  ('Greenlam', 'Titterton', '7g9pNewjqWo', 'mtitterton1c@cnet.com') ,
  ('Flowdesk', 'Bostock', '6mOCdmxs2u', 'abostock1d@i2i.jp') ,
  ('It', 'Chetwind', 'gHBzPY7IJash', 'achetwind1e@yale.edu') ,
  ('Redhold', 'Haug', 'gZgolX6FozV3', 'mhaug1f@comsenz.com') ,
  ('Tresom', 'Pulman', 'RhcjYRaQVljY', 'upulman1g@alibaba.com') ,
  ('Matsoft', 'Valentine', 'sikIpBNcP9E2', 'rvalentine1h@multiply.com') ,
  ('Tampflex', 'Christaeas', 'i5FzKRKkb', 'lchristaeas1i@sitemeter.com') ,
  ('Bytecard', 'Priestland', 'kB9znYDiE0F', 'fpriestland1j@yale.edu') ,
  ('Voyatouch', 'Olivazzi', 'MFfr5VoF8LD2', 'jolivazzi1k@bbb.org') ,
  ('Konklab', 'Levis', '8iIn7O', 'clevis1l@va.gov') ,
  ('Job', 'Thorrold', 'hc0psCgm', 'ethorrold1m@nature.com') ,
  ('Tempsoft', 'Southerns', 'Kw2E4KyBTe', 'ksoutherns1n@wufoo.com') ,
  ('Redhold', 'Gainforth', 'HzC0sUUW', 'igainforth1o@washington.edu') ,
  ('Temp', 'Saltsberg', 'yWZ9MvE4a', 'csaltsberg1p@mashable.com') ,
  ('Y-Solowarm', 'Caswall', '1hkZZaoR', 'scaswall1q@bandcamp.com') ,
  ('Sonair', 'Arp', 'jWzULHXC', 'darp1r@sina.com.cn') ,
  ('Voyatouch', 'Dunmore', 'V0uAWkwma8', 'vdunmore1s@livejournal.com') ,
  ('Lotlux', 'Seven', 'Jf0DHOhiO6qN', 'kseven1t@upenn.edu') ,
  ('Bitwolf', 'Odhams', 'GCXC6GHTDG', 'codhams1u@unesco.org') ,
  ('Tin', 'Gaskin', '0aO5sgLS', 'dgaskin1v@usda.gov') ,
  ('Y-find', 'Baldini', '84i0FOgDUc', 'dbaldini1w@opera.com') ,
  ('Sonair', 'Ainsby', 'fFMrOkKV', 'bainsby1x@salon.com') ,
  ('Lotstring', 'Blagdon', '0TFYtc2', 'dblagdon1y@addtoany.com') ,
  ('Solarbreeze', 'Chase', 'RAECVifS', 'tchase1z@livejournal.com') ,
  ('Fintone', 'Huxster', 'N0AigAh', 'nhuxster20@bloglovin.com') ,
  ('Y-Solowarm', 'Gabbatiss', 's8FaQtU7rL', 'hgabbatiss21@kickstarter.com') ,
  ('Bitchip', 'Cootes', 'SkfcfT8YHCt', 'fcootes22@latimes.com') ,
  ('Cookley', 'Dearnly', 'X7dSI0O31Azt', 'gdearnly23@bizjournals.com') ,
  ('Hatity', 'Pleavin', 'uPfUDJ6zgLL', 'dpleavin24@diigo.com') ,
  ('Konklab', 'Brasse', 'PKPCdMQ', 'abrasse25@netvibes.com') ,
  ('Job', 'Gateman', 'CZKK7sGZBWf', 'mgateman26@g.co') ,
  ('Bamity', 'Sinfield', 'gigPVm', 'asinfield27@apple.com') ,
  ('Toughjoyfax', 'Antonignetti', 'oORBHdl', 'kantonignetti28@lulu.com') ,
  ('Bamity', 'Dullaghan', 'GY5V32', 'adullaghan29@elpais.com') ,
  ('Quo Lux', 'M''Quharg', 'ExqAad0mhIka', 'tmquharg2a@irs.gov') ,
  ('Fintone', 'Monkeman', 'nlLNRpnPFwK', 'smonkeman2b@virginia.edu') ,
  ('Zontrax', 'Pender', 'MlqlV1U', 'dpender2c@google.co.uk') ,
  ('Viva', 'Wolpert', 'zdgtzh5', 'bwolpert2d@angelfire.com') ,
  ('Konklux', 'Grishkov', 'EYg2TcYUho', 'pgrishkov2e@domainmarket.com') ,
  ('Tempsoft', 'Aylmore', 'TIeZpIagzJvT', 'laylmore2f@comsenz.com') ,
  ('Overhold', 'Warbeys', '1yqcpHsN', 'kwarbeys2g@studiopress.com') ,
  ('Sub-Ex', 'Bchessy', 'owqjRsJjzGp', 'wbeagley2h@opera.com') ,
  ('Job', 'Mixworthy', 'Tdzst5', 'smixworthy2i@ted.com') ,
  ('Toughjoyfax', 'Bartholomew', 'hKJSOqw', 'kbartholomew2j@spotify.com') ,
  ('Bigtax', 'Blissitt', 'DyDykYJO', 'wblissitt2k@prnewswire.com') ,
  ('Vagram', 'Pulteneye', 'loPYretTTTx', 'jpulteneye2l@chicagotribune.com') ,
  ('Tresom', 'Legrice', 'jhhH4F', 'tlegrice2m@scribd.com') ,
  ('Voltsillam', 'Kennefootball', 'C06TSZY', 'nkennefootball2n@flavors.me') ,
  ('Cardify', 'Cathee', '51zxaHjoqWgK', 'mcathee2o@vk.com') ,
  ('Tres-Zap', 'Seabright', 'Syan4ZmbofqL', 'lseabright2p@mapquest.com') ,
  ('Mat Lam Tam', 'Wheatcroft', 'LVDGba4Si', 'cwheatcroft2q@msu.edu') ,
  ('Solarbreeze', 'Attoc', 'cAY5hj7', 'oattoc2r@ning.com');

INSERT INTO teams (name, location, user_id, size, genders, ages, skill, sport, solo) VALUES
('fac',  'london',  '1',   '1', '3', '1', '3',  'football',  true),
 ('Otcom', 'Darvi',  '3',  '3',  '1',  '2',  '1', 'cricket', false),
 ('Sub-Ex', 'Qiaosi',  '7',  '8',  '3',  '4',  '3', 'chess', true),
 ('Opela', 'Ballybofey',  '5',  '18',  '2',  '3',  '2', 'football', false),
 ('Quo Lux', 'Nanjie',  '2',  '12',  '1',  '4',  '3', 'volleyball', true),
 ('Fintone', 'Cibitung',  '3',  '3',  '2',  '3',  '2', 'volleyball', false),
 ('Ventosanzap', 'Tomislavgrad',  '8',  '5',  '4',  '2',  '1', 'volleyball', true),
 ('Flowdesk', 'Songying',  '8',  '11',  '1',  '4',  '3', 'football', false),
 ('Biodex', 'Kisasa',  '6',  '3',  '1',  '3',  '2', 'checkers', true),
 ('Zamit', 'Non Sila',  '7',  '17',  '2',  '4',  '2', 'water polo', false),
 ('Home Ing', 'Shemursha',  '9',  '6',  '2',  '3',  '3', 'water polo', false),
 ('Bigtax', 'Shouchun',  '1',  '22',  '2',  '4',  '3', 'water polo', false),
 ('Duobam', 'Pābna',  '2',  '22',  '1',  '2',  '1', 'water polo', true),
 ('Rank', 'Xingang',  '7',  '2',  '1',  '2',  '1', 'checkers', true),
 ('Vagram', 'Kralice na Hané',  '6',  '5',  '3',  '2',  '1', 'rugby', false),
 ('Rank', 'Jiupu',  '10',  '3',  '1',  '1',  '2', 'rugby', true),
 ('Bytecard', 'Guacarí',  '6',  '13',  '4',  '4',  '3', 'rugby', true),
 ('Konklux', 'Brignoles',  '3',  '19',  '4',  '1',  '3', 'checkers', true),
 ('Kanlam', 'Nkove',  '1',  '11',  '4',  '1',  '3', 'rugby', true),
 ('Subin', 'Changning',  '3',  '17',  '2',  '2',  '2', 'football', false),
 ('Zoolab', 'Shekou',  '9',  '9',  '1',  '1',  '3', 'checkers', true),
 ('Domainer', 'Carnot',  '8',  '10',  '4',  '3',  '2', 'football', true),
 ('It', 'Novokuybyshevsk',  '2',  '15',  '3',  '4',  '1', 'football', false),
 ('Stim', 'Aix-en-Provence',  '3',  '6',  '2',  '2',  '1', 'football', false),
 ('Home Ing', 'Carbajales',  '10',  '5',  '1',  '2',  '1', 'football', true),
 ('Bytecard', 'Nginjen',  '4',  '2',  '2',  '1',  '2', 'volleyball', false),
 ('Transcof', 'Cikaung',  '3',  '10',  '4',  '4',  '1', 'football', true),
 ('Quo Lux', 'Limanancong',  '6',  '3',  '1',  '3',  '2', 'football', false),
 ('Redhold', 'Tianjiazhai',  '1',  '1',  '1',  '1',  '1', 'football', false),
 ('Stringtough', 'Al ‘Awjah',  '10',  '12',  '2',  '2',  '2', 'football', true),
 ('Flexidy', 'Sapareva Banya',  '4',  '21',  '1',  '3',  '2', 'checkers', true);

INSERT INTO events(name, sport, users_id, location, genders, open) VALUES
('fun at the park','Football', '1', 'london', '3', true ),
 ('Zontrax', 'football', '72', 'Kizhinga', '4', false),
 ('Cardguard', 'football', '93', 'Trzcinica', '4', true),
 ('Span', 'football', '88', 'Gandapura', '4', true),
 ('Wrapsafe', 'rugby', '76', 'Gangkou', '1', true),
 ('Overhold', 'water polo', '95', 'Niort', '2', false),
 ('Namfix', 'rugby', '44', 'Guangshun', '3', false),
 ('Stim', 'football', '35', 'Dagar', '2', false),
 ('Vagram', 'rugby', '3', 'Chechen-Aul', '4', true),
 ('Bitchip', 'rugby', '58', 'Aygestan', '3', false),
 ('Biodex', 'football', '56', 'Spasskoye-Lutovinovo', '3', false),
 ('Keylex', 'rugby', '82', 'Rujewa', '3', true),
 ('Matsoft', 'rugby', '43', 'Andilamena', '2', true),
 ('Rantk', 'rugby', '38', 'Pecoro', '1', true),
 ('Tin', 'rugby', '17', 'Lewoluo', '1', true),
 ('Zaam-Dox', 'football', '24', 'Piancheng', '4', true),
 ('Otcom', 'water polo', '97', 'Krasica', '1', false),
 ('Lotlux', 'water polo', '10', 'Zhaobei', '2', true),
 ('Gembucket', 'football', '54', 'Teminabuan', '1', true),
 ('Hatity', 'football', '90', 'Guarapuava', '1', true),
 ('Bamity', 'rugby', '32', 'Xinbu', '1', false),
 ('Fixflex', 'football', '82', 'Dushu', '2', false),
 ('Subin', 'football', '56', 'Woloara', '4', true),
 ('Pannier', 'rugby', '11', 'Nikol’sk', '2', false),
 ('Fix San', 'rugby', '65', 'Bom Jesus dos Perdões', '4', true),
 ('Alphazap', 'football', '71', 'Baoshan', '4', false),
 ('Opela', 'football', '84', 'Yaguachi Nuevo', '1', false),
 ('Regrant', 'football', '5', 'Baihe', '1', true),
 ('Lotlux', 'football', '87', 'Lékoni', '4', false),
 ('Tempsoft', 'rugby', '79', 'Årjäng', '3', true),
 ('Tempsoft', 'rugby', '84', 'Souq Larb’a al Gharb', '3', false);

COMMIT;
